#ifndef DEFLATE_H
#define DEFLATE_H

#include <string>
#include <vector>
#include <cstdint>
#include "../common/Metrics.h"

/**
 * @brief Token generated by the LZ77 stage and consumed by the Huffman stage.
 */
struct LZ77Token {
    bool isMatch;          // false = Literal byte, true = (Distance, Length) match
    uint8_t literal;       // Literal byte value if isMatch == false
    uint16_t length;       // Match length if isMatch == true
    uint16_t distance;     // Match backward distance if isMatch == true

    static LZ77Token createLiteral(uint8_t byte) {
        LZ77Token token;
        token.isMatch = false;
        token.literal = byte;
        token.length = 0;
        token.distance = 0;
        return token;
    }

    static LZ77Token createMatch(uint16_t length, uint16_t distance) {
        LZ77Token token;
        token.isMatch = true;
        token.literal = 0;
        token.length = length;
        token.distance = distance;
        return token;
    }
};

class Deflate {
public:
    // =========================================================================
    // MEMBER 1 RESPONSIBILITY: Huffman Entropy Coding & Bit Packaging for Tokens
    // =========================================================================
    /**
     * @brief Encodes a sequence of LZ77 tokens into a compressed bitstream using Huffman Coding.
     * @param tokens The vector of LZ77 tokens (literals and matches).
     * @param out The destination output stream.
     */
    static void encodeTokensWithHuffman(const std::vector<LZ77Token>& tokens, uint64_t originalSize, std::ostream& out);

    /**
     * @brief Decodes a compressed bitstream back into a sequence of LZ77 tokens.
     * @param in The source input stream.
     * @param originalSize Output parameter to retrieve original uncompressed size.
     * @return Vector of decoded LZ77 tokens.
     */
    static std::vector<LZ77Token> decodeTokensWithHuffman(std::istream& in, uint64_t& originalSize);

    // =========================================================================
    // MEMBER 2 & 3 RESPONSIBILITIES: LZ77 Sliding Window Compression & Decompression
    // =========================================================================
    /**
     * @brief Performs LZ77 sliding window matching on raw input bytes.
     * Assigned to Member 2.
     */
    static std::vector<LZ77Token> lz77Compress(const std::vector<uint8_t>& input);

    /**
     * @brief Reconstructs uncompressed byte stream from LZ77 tokens.
     * Assigned to Member 3.
     */
    static std::vector<uint8_t> lz77Decompress(const std::vector<LZ77Token>& tokens);

    // =========================================================================
    // HIGH-LEVEL DEFLATE PIPELINE (LZ77 -> Huffman -> Output)
    // =========================================================================
    static CompressionMetrics compress(const std::string& inputPath, const std::string& outputPath);
    static CompressionMetrics decompress(const std::string& inputPath, const std::string& outputPath);
};

#endif // DEFLATE_H
